### ISSUE TITLE
PerformanceAudit kills my server

### ISSUE THREAD

**Issue by almare** [DevDavido/performance-audit-plugin#31]
At first great plugin and after correct setup the audit works really good. My problem was after setup that my server gets killed a day after installing the plugin. The problem looks like that all matomo sites starts the audit at the same time. This kills my server.
 
Is it possible to run the audit one by one and not all sites at the same time. Ideally it would be nice to run it for example at 3.00 o'clock in the night?

Server: 8 core / 16gb ram

**Comment by DevDavido** [comment]
Thanks for the feedback. Do you run multiple Matomo instances on one server?
The plugin runs the audits sequentially after each other per Matomo instance in order to avoid too much pressure on any server. The time the daily audit process starts is after (UTC) midnight.

This timing behaviour could be made customizable, anyone feel free to contribute a PR.

**Comment by almare** [comment]
Thank you for your reply. There is only one instance running. Do you have an idea what can cause that one job is not finished? Maybe I should mention that one site has over 200000 pages :-). Finally I disabled that from running PerformanceAudits.

**Comment by DevDavido** [comment]
In some cases, lighthouse audit processes are not terminated, but a timeout should occur after 60 seconds per default. This should be the exception rather than the rule. That timeout only happens if the lighthouse audit process is not in a loop. Do you have a chance to monitor the jobs and its parent process? Having over 200000 pages definitely contributes to very long audit processes. :) Are they generally unique or just differ in their URL query string?
