### ISSUE TITLE
PerformanceAudit - Functions deprecated

### ISSUE THREAD

**Issue by nicoco59** [DevDavido/performance-audit-plugin#42]
Hi,

I'm currently using Matomo 4.13.1 and I'm having an issue while enabling the plugin, it seems to prevent the cron tasks to work properly, here is the error when I navigate to the "Plugin check" section :

WARNING: /plugins/PerformanceAudit/vendor/symfony/process/Process.php(612): Deprecated - Return type of Symfony\Component\Process\Process::getIterator($flags = 0) should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice - Matomo 4.13.1 - Please report this message in the Matomo forums: https://forum.matomo.org/ (please do a search first as it might have been reported already) (Module: PerformanceAudit, Action: pluginCheck, In CLI mode: false)

Did someone run into this issue before ? How to solve it ?

Thanks.

**Comment by DevDavido** [comment]
Hi @nicoco59, 

What PHP version do you use? What NPM version? Are all [requirements](https://github.com/DevDavido/performance-audit-plugin#minimum-requirements) installed? Do you have PHP error logs with a stack trace of that deprecation warning or other errors?

That warning itself occurs since PHP 8.1 is available. Please note that this plugin has not been tested (yet) with PHP 8 and above due to limited time, but feel free to open up a PR.

Which cron tasks are you referring to? Do you mean the [scheduled tasks from Matomo](https://developer.matomo.org/guides/scheduled-tasks)? Or the cron jobs from your OS? Does deactivating this plugin resolve the cron tasks issue? How many sites do you monitor with Matomo? How many pages does each site contain on average?

With more information it's clearer to find the underlying issue.

**Comment by nicoco59** [comment]
Hi @DevDavido , here's my server's configuration and details :
- PHP : 8.1.8
- We upgraded the NPM so the plugin could be installed and activated (so at least NPM 6.13)
- We set up a cron task from our OS, which runs every hour by following the steps here : https://matomo.org/faq/on-premise/how-to-set-up-auto-archiving-of-your-reports/ 
- Deactivating your plugin indeed resolve the issue
- We monitor 5 sites with Matomo
- First site contains around 1600 pages, the others around 200 pages

**Comment by DevDavido** [comment]
Thanks for the information @nicoco59. What are the server specs (CPU, RAM) you're running Matomo on? Keep in mind that those performance audit can be quite resource intensive.
Did you use the default configuration of the plugin or were any custom settings used?

Would you try to disable the performance audit for each website except the smallest one (e.g. the mentioned 200 page site) in the website settings and let me know if this working for that website as expected?

The PHP warning itself definitely comes from using PHP 8.1 in this case, but shouldn't affect the overall plugin functionality.

**Comment by nicoco59** [comment]
Thanks for your answer, we're currently running with 16v CPU and 16gb of ram for the database and 6 CPU / 8gb of ram for the API.

I changed the configuration that way : 
- Increase timeout for performance audits
- Performance simulation environment for Desktop & Mobile
- Group URLs for performance audits which only differ in their query string

I enabled the plugin only for our blogs so it won't have an impact on the server's performance.

I'll get back to you after I get some results, it would be interesting to be able to check only the pages we're interested in and not the whole site.

I'll open a feature request about it.
